Better logging

diff --git a/src/bin/docker-make b/src/bin/docker-make
--- a/src/bin/docker-make
+++ b/src/bin/docker-make
@@ -5,9 +5,11 @@ if grep -q docker /proc/self/cgroup; then
 fi
 
 dir=$PWD
+CMD=${0##*/}
 DOCKER_CONTAINER_ID=
 while test -z "$DOCKER_CONTAINER_ID"; do
   if test -e $dir/.dockerrc; then
+    echo "$CMD: found $dir/.dockerrc" 1>&2
     . $dir/.dockerrc
   fi
   dir=${dir%/*}
@@ -16,11 +18,11 @@ done
 
 if test "$DOCKER_CONTAINER_ID"; then
   if docker inspect "$DOCKER_CONTAINER_ID" 1>/dev/null 2>&1; then
-    echo "$0: using docker container $DOCKER_CONTAINER_ID"
+    echo "$CMD: using docker container $DOCKER_CONTAINER_ID" 1>&2
     cmd="IFS=; set -e; . ~/.bash_profile; cd $PWD; /usr/bin/make"$(printf " %q" "$@")
     exec docker exec $DOCKER_CONTAINER_ID /bin/bash -c "$cmd"
   else
-    echo "$0: *** invalid docker container $DOCKER_CONTAINER_ID" 1>&2
+    echo "$CMD: *** invalid docker container $DOCKER_CONTAINER_ID" 1>&2
     exit 1
   fi
 else
